import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import RootBody from '@/components/RootBody';
import React from 'react';
import { userService } from '@/services/user-service';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const response = await userService.readById();

    return (
        <html lang="en" className="w-full h-full">
            <body
                className={`w-full h-full ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {response.user ? 
                    <RootBody user={response.user}>{children}</RootBody>
                    :
                    <div>user not found</div>
                }
            </body>
        </html>
    );
}
