import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface Link {
    name: string;
    href: string;
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className='w-full h-full'>
            <body className={`w-full h-full ${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex flex-col justify-center items-center">
                    <NavBar />

                    {children}
                </div>
            </body>
        </html>
    );
}
